runtime: python37

handlers:
  # This to configure Google App Engine to serve the files in the app's static directory
  - url: /static
    static_dir: static


  #T his handler routes all requests not caught above to the main app. It is requred when static routes are defined, but can be omitted (along with entire handlers section) when there are no static files defined.

  - url: /.*
    script: auto